name: commons_dependencies
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
    # git:
    #   url: https://github.com/google/charts.git
    #   path: charts_flutter
  permission_handler: ^9.2.0
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  intl: ^0.17.0
  location: ^4.3.0
  geolocator: ^8.2.1
  font_awesome_flutter: ^10.1.0
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+2
  flutter_modular: ^5.0.2
  dio: ^4.0.6
  google_maps_flutter: ^2.1.5
  flutter_polyline_points: ^1.0.0
  connectivity_plus: ^2.3.6
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.commons_dependencies
    iosBundleIdentifier: com.example.commonsDependencies
